name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - PR  # è®¾ç½®è§¦å‘éƒ¨ç½²çš„åˆ†æ”¯

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # è¿è¡Œåœ¨æœ€æ–°çš„ Ubuntu ç³»ç»Ÿ
    if: ${{github.branch}} == 'PR'
    steps:
    - name: Checkout source
      uses: actions/checkout@v2  # æ£€å‡ºä»£ç 

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # ä½¿ç”¨ Node.js ç‰ˆæœ¬ 14
      
    - name: ç¼“å­˜ VUE
      uses: actions/cache@v3
      id: cache
      with:
        path: 
          ./web/node_modules
        key: ${{runner.OS}}-${{hashFiles('**/web/package-lock.json')}}
          
    - name: å®‰è£…ä¾èµ–
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd web
        npm install

    - name: Deploy Blog
      run: | 
        cd web
        npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages  # éƒ¨ç½²åˆ° gh-pages åˆ†æ”¯
        folder: web/dist  # æ„å»ºè¾“å‡ºçš„ç›®å½•

    - name: ğŸ“‚ Sync files
      if: ${{ secrets.FTP_USERNAME }} == 'xieying996'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./web/dist/
        server-dir: ./
        log-level: verbose
