name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - PR  # è®¾ç½®è§¦å‘éƒ¨ç½²çš„åˆ†æ”¯

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # è¿è¡Œåœ¨æœ€æ–°çš„ Ubuntu ç³»ç»Ÿ
    steps:
    - name: Checkout source
      uses: actions/checkout@v2  # æ£€å‡ºä»£ç 

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # ä½¿ç”¨ Node.js ç‰ˆæœ¬ 14
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
            java-version: 21    

    - name: ç¼“å­˜ VUE
      uses: actions/cache@v3
      id: cache
      with:
        path: 
          ./web/node_modules
        key: ${{runner.OS}}-${{hashFiles('**/web/package-lock.json')}}
          
    - name: å®‰è£…ä¾èµ–
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd web
        npm install



    - name: Install Cordova
      run: npm install -g cordova

    - name: æ„å»ºCordovaé¡¹ç›®
      run: |
          cd web
          cordova create CordovaProject work.xiey.build bcbcbc
          cd CordovaProject
          cordova platform add android
          cordova plugin add cordova-plugin-webview
          cordova plugin add cordova-plugin-statusbar
          npm i

    - name: build Blog
      run: | 
            cd web
            npm run build



    - name: é…ç½®è®¾ç½®
      run: |
          mv config.xml web/CordovaProject/config.xml
          cd web/CordovaProject/
          cordova build android
          

    - name: Upload dev APK
      uses: actions/upload-artifact@v1
      with:
          name: app-dev
          path: web/CordovaProject/platforms/android/app/build/outputs/apk/debug/app-debug.apk
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages  # éƒ¨ç½²åˆ° gh-pages åˆ†æ”¯
        folder: web/CordovaProject/www  # æ„å»ºè¾“å‡ºçš„ç›®å½•

    - name: ğŸ“‚ Sync files
      if: github.repository != 'FantasyRL/bocchi-the-travel'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./web/CordovaProject/www/
        server-dir: ./
        log-level: verbose
